IS-21439: Add a test mode to docker-run and docker-build commands
Add support for --link and args in the docker-run command.

diff --git a/files/usr/local/bin/docker-run b/files/usr/local/bin/docker-run
--- a/files/usr/local/bin/docker-run
+++ b/files/usr/local/bin/docker-run
@@ -5,7 +5,7 @@ DOCKER_IMAGE_REPOSITORY="centile"
 DOCKER_BUILD_DIRECTORY="/etc/docker"
 
 usage() {
-    echo Usage: $0 [ -c cluster] [ -i image ] name [name [...]]
+    echo Usage: $0 [ -c cluster] [ -i image ] [-t] name [name [...]]
     echo -e "Run a docker from an image in the '${DOCKER_IMAGE_REPOSITORY}' repository."
     echo  
     echo -e "name\t is a directory with a Dockerfile, default in '${DOCKER_BUILD_DIRECTORY}/name'."
@@ -15,7 +15,8 @@ usage() {
     echo -e "Options:"
     echo -e "\t-c 'cluster'\tAllow to override files in 'image' directory with existing files in"
     echo -e "\t\t\tthe 'image/cluster' directory."
-    echo -e "\t -i 'image'\tis a directory with a Dockerfile, default in '${DOCKER_BUILD_DIRECTORY}/image'."
+    echo -e "\t -i 'image'\tthe docker image to run, default in '${DOCKER_IMAGE_REPOSITORY}' repository."
+    echo -e "\t -t\t\ttest mode, output the command that would be launched."
     echo
     echo -e "EXAMPLES"
     echo 
@@ -39,6 +40,8 @@ while [ $# -gt 0 ]; do
         ;;
         -h|--help) usage
         ;;
+        -t|--test) TEST=1
+        ;;
         *) args="${args:-} $1"
     esac
     shift
@@ -46,16 +49,30 @@ while [ $# -gt 0 ]; do
 done
 
 for arg in ${args}; do
+    # reset args
+    image=""
     # extract docker name
     name="$(basename ${arg})"
     # keep part before the dash as the directory name
     dir="$(dirname ${arg})/${name%-*}"
     # keep part after the dash as an image suffix name
     [ "${name##*-}" != "${name}" ] && suffix="${name##*-}"
-    # set docker image
-    [ -n "${IMAGE}" ] && image="${IMAGE}"
-    # if image is not provided, set docker name as image and if image does not exists, try without suffix
-    [ -z "${IMAGE}" ] && image="${name}" && [ -z "$(docker images 2>/dev/null |awk '$1 == "'${DOCKER_IMAGE_REPOSITORY}/${image}'" {print $1}')" ] && image="${image%-*}"
+    # if provided, set docker image from args
+    if [ -n "${IMAGE}" ]; then
+        # if docker image does not contain a /, add our default repository
+        [ "${IMAGE##*/}" != "${IMAGE}" ] && image="${IMAGE}" || image="${DOCKER_IMAGE_REPOSITORY}/${IMAGE}"
+    # else try to find an image from the docker name
+    else
+        # try docker name, docker name without ending numbers, docker name without suffix
+        for image in ${name} ${name%%[0-9]*} ${name%-*}; do
+            # search for image in ${DOCKER_IMAGE_REPOSITORY}
+            [ -n "$(docker images 2>/dev/null |awk '$1 == "'${DOCKER_IMAGE_REPOSITORY}/${image}'" {print $1}')" ] && image="${DOCKER_IMAGE_REPOSITORY}/${image}" && break
+            image="${name}"
+        done
+    fi
+
+    tag="$(docker images |awk '$1 == "'${image}'" {print $2}')"
+    [ -z "${tag}" ] && echo "ERROR: Cannot find image '${image}'" && exit 2
 
     # default to ${DOCKER_BUILD_DIRECTORY}/${dir} if ${dir} does not exists
     [ ! -d "${dir}" ] && [ -d "${DOCKER_BUILD_DIRECTORY}/${dir}" ] && dir="${DOCKER_BUILD_DIRECTORY}/${dir#./}"
@@ -64,9 +81,6 @@ for arg in ${args}; do
     [ -d ${dir} ] && [ -f "${dir}/Dockerfile" ] || usage
     # cluster directory exists
     [ -n "${CLUSTER}" ] && { [ -d ${dir}/${CLUSTER} ] || usage; }
-
-    tag="$(docker images |awk '$1 == "'${DOCKER_IMAGE_REPOSITORY}/${image}'" {print $2}')"
-    [ -z "${tag}" ] && echo "ERROR: Cannot find image '${DOCKER_IMAGE_REPOSITORY}/${image}'" && exit 2
 
     # search for Dockeropts files
     files="${dir}/Dockeropts ${dir}/Dockeropts-${suffix}"
@@ -83,10 +97,13 @@ for arg in ${args}; do
     done
 
     # extract DOCKER_OPT
-    [ -n "${DOCKER_OPT}" ] && DOCKER_OPTS="${DOCKER_OPTS} --${DOCKER_OPT/ / --}"
+    [ -n "${DOCKER_OPT}" ] && DOCKER_OPTS="--${DOCKER_OPT/ / --}"
 
     # extract DOCKER_ENV
     [ -n "${DOCKER_ENV}" ] && DOCKER_OPTS="${DOCKER_OPTS} -e ${DOCKER_ENV//\" /\" -e }"
+
+    # extract DOCKER_LINK
+    [ -n "${DOCKER_LINK}" ] && DOCKER_OPTS="--link ${DOCKER_LINK/ / --link }"
 
     # extract DOCKER_PORT
     [ -n "${DOCKER_PORT}" ] && DOCKER_OPTS="${DOCKER_OPTS} -p ${DOCKER_PORT// / -p }"
@@ -103,8 +120,12 @@ for arg in ${args}; do
     done
 
     # launch docker
-    eval docker run --restart=always ${DOCKER_OPTS} -d --name ${name} ${DOCKER_IMAGE_REPOSITORY}/${image}
-    result=$?
+    if [ ${TEST} ]; then
+        echo docker run --restart=always ${DOCKER_OPTS} -d --name ${name} ${image} ${DOCKER_RUN:-}
+    else
+        eval docker run --restart=always ${DOCKER_OPTS} -d --name ${name} ${image} ${DOCKER_RUN:-}
+        result=$?
+    fi
     [ ${result:-0} -ge ${return:-0} ] && return=${result}
 done
 
